api:
  identifier: 'Hoxware Server'
  port: 5002

logger:
  options:
    level: trace

db:
  name: suspensiones
  user: demoUser
  password: demoPassword
  host: localhost
  port: 5432

key:
  secret: "52d726b159902f9884b2e95dfcb028ce8d7aa51865f1fb5daa105dc30120cddf"
  algorithm: "aes-256-cbc"

jwt:
  accessTokenSecret: '0d7c5c5f-768c-4d98-8900-13aadaa21937'
  refreshTokenSecret: '1a7v8c0l-391k-1f82-4492-tha3taa11334'
  accessTokenLife: '30d'
  refreshTokenLife: 2592000

email:
  user: 'gustavoayumu@gmail.com'
  password: 'kmjs ajgq psox hnhr'
  smtpHost: 'smtp.gmail.com'
  smtpPort: 465

image:
  baseUrl: 'http://localhost:5002/project'
  uploadDir: '../uploads/projects'
  default: '../uploads/defaults'
  #uploadDir: '/Users/warsystem/Desktop/hoxware/api-hoxware-back/src/uploads/projects'

serverNameFront: 'http://localhost:4200/'


